return {
  {
    "nvim-treesitter/nvim-treesitter",
    version = false,
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile", "BufWritePre", "VeryLazy" },
    -- dependencies = {
    -- 	{ "nvim-treesitter/nvim-treesitter-textobjects" },
    -- },
    main = "nvim-treesitter.configs", -- Sets main module to use for opts
    -- [[ Configure Treesitter ]] See `:help nvim-treesitter`
    -- lazy = vim.fn.argc(-1) == 0, -- load treesitter early when opening a file from the cmdline
    cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
    -- keys = {
    -- 	{ "<c-space>", desc = "Increment Selection" },
    -- 	{ "<bs>", desc = "Decrement Selection", mode = "x" },
    -- },
    opts = {
      ensure_installed = {
        "astro",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "cpp",
        "csv",
        "css",
        "diff",
        "dockerfile",
        "editorconfig",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "graphql",
        "html",
        "hyprlang",
        "javascript",
        "jsdoc",
        "json5",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "nginx",
        "ninja",
        "php",
        "phpdoc",
        "prisma",
        "proto",
        "python",
        "query",
        "rust",
        "ron",
        "rst",
        "scss",
        "sql",
        "svelte",
        "tsx",
        "typescript",
        "toml",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
        "xml",
      },
      -- Autoinstall languages that are not installed
      auto_install = false,
      highlight = {
        enable = true,
        -- Some languages depend on vim's regex highlighting system (such as Ruby) for indent rules.
        --  If you are experiencing weird indenting issues, add the language to
        --  the list of additional_vim_regex_highlighting and disabled languages for indent.
        additional_vim_regex_highlighting = { "ruby" },
      },
      indent = { enable = true, disable = { "ruby" } },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    },
  },
}
